### ISSUE TITLE
Unable to import highdicom in Mac

### ISSUE THREAD

**Issue by elamathis18** [herrmannlab/highdicom#145]
Hi,

I'm unable to import highdicom after the installation. Here are some logs.
```

python3 -m pip install highdicom --ignore-installed
Defaulting to user installation because normal site-packages is not writeable
Collecting highdicom
  Using cached highdicom-0.14.0-py3-none-any.whl (697 kB)
Collecting pylibjpeg-libjpeg>=1.2
  Using cached pylibjpeg_libjpeg-1.3.0-cp38-cp38-macosx_11_0_arm64.whl (1.6 MB)
Collecting pydicom>=2.2.2
  Using cached pydicom-2.2.2-py3-none-any.whl (2.0 MB)
Collecting pylibjpeg>=1.3
  Using cached pylibjpeg-1.4.0-py3-none-any.whl (28 kB)
Collecting pillow-jpls>=1.0
  Using cached pillow_jpls-1.1.0-cp38-cp38-macosx_11_0_arm64.whl (71 kB)
Collecting pylibjpeg-openjpeg>=1.1
  Using cached pylibjpeg_openjpeg-1.2.0-cp38-cp38-macosx_11_0_arm64.whl (581 kB)
Collecting numpy>=1.19
  Using cached numpy-1.22.1-cp38-cp38-macosx_11_0_arm64.whl (12.7 MB)
Collecting pillow>=8.3
  Using cached Pillow-9.0.0-cp38-cp38-macosx_11_0_arm64.whl (2.7 MB)
Installing collected packages: pillow, numpy, pylibjpeg-openjpeg, pylibjpeg-libjpeg, pylibjpeg, pydicom, pillow-jpls, highdicom
Successfully installed highdicom-0.14.0 numpy-1.22.1 pillow-9.0.0 pillow-jpls-1.1.0 pydicom-2.2.2 pylibjpeg-1.4.0 pylibjpeg-libjpeg-1.3.0 pylibjpeg-openjpeg-1.2.0

```

```
python3
Python 3.8.9 (default, Oct 26 2021, 07:25:53) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import highdicom as hd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/highdicom/__init__.py", line 4, in <module>
    from highdicom import legacy
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/highdicom/legacy/__init__.py", line 4, in <module>
    from highdicom.legacy.sop import (
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/highdicom/legacy/sop.py", line 18, in <module>
    from highdicom.frame import encode_frame
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/highdicom/frame.py", line 6, in <module>
    import pillow_jpls  # noqa
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/pillow_jpls/__init__.py", line 2, in <module>
    from .jpls_image_file import JplsImageFile, accept
  File "/Users/elamathis/Library/Python/3.8/lib/python/site-packages/pillow_jpls/jpls_image_file.py", line 3, in <module>
    from . import _pycharls
ImportError: dlopen(/Users/elamathis/Library/Python/3.8/lib/python/site-packages/pillow_jpls/_pycharls.cpython-38-darwin.so, 2): Symbol not found: __ZN3fmt2v87vformatENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE
  Referenced from: /Users/elamathis/Library/Python/3.8/lib/python/site-packages/pillow_jpls/_pycharls.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/elamathis/Library/Python/3.8/lib/python/site-packages/pillow_jpls/_pycharls.cpython-38-darwin.so
>>> 

```

**Note**: I tried completely uninstalling and installing the package but the problem persists.

**Comment by CPBridge** [comment]
Sorry about your issue and thanks for reporting it. It appears that this issue is nothing to do with highdicom (which is a pure Python library). In fact the import is failing on the line `import pillow_jpls`. I will try to reproduce your issue soon, but in the meantime you might like to test whether you can `import pillow_jpls` outside of highdicom but in your environment and, if you can't, open an issue on the [`pillow-jpls`](https://github.com/planetmarshall/pillow-jpls)t, which is a dependency of pydicom as you may get more useful help there.

Could you also please provide some more information about your setup, including how you installed this version of python, and any virtual environment management you are using? That will help narrow down the issue. Thank you

**Comment by CPBridge** [comment]
I am unable to reproduce this issue on my mac (11.6 Big Sur) using Python 3.8.9 installed through pyenv and the same list of packages as the OP installed in a fresh virtualenv (through pyenv-virtualenv). Everything imports correctly as expected.

We would probably need more information about the OP's environment to debug

**Comment by CPBridge** [comment]
I have now come across related issues a few times myself concerning the openjpeg import. To anyone who has this problem my recommendations are:

- Start with a fresh python environment (e.g. a new virtualenv if possible)
- Make sure pip is updated to the latest version in your environment
- Reinstall highdicom and all other packages

I'll leave this open for a little longer in case @elamathis18 has other issues they want to raise or report

**Comment by hackermd** [comment]
Thanks @CPBridge for sharing the insight.

Since these libraries are causing issues upon installation on certain platforms/environments, I am wondering whether we should make them optional. They are only required to encode/decode data using specific transfer syntaxes and many users won't need them. When a user attempts to encode/decode data with a transfer syntax that would require one of these libraries, we could raise an error with a message informing the user to install the package with the extra requirements (e.g., `f'To use transfer syntax "{transfer_syntax_uid}", install the library with "pip install highdicom[{extra_requirement}]"'`)

**Comment by CPBridge** [comment]
I think it's an option we should bear in mind, but I also don't want to overreact to an issue that hopefully will stabilise as these packages mature. I think we should continue to monitor and see whether similar issues continue to occur

**Comment by CPBridge** [comment]
Closing this issue due to lack of activity
